### ISSUE TITLE
Adding of an additional value "Grid - Output power"

### ISSUE THREAD

**Issue by ghost** [H2CK/hm_kostalpiko#2]
Hi,

might it be possible to implement an additional value in the next release to monitor the amount of W that is actually sent to the grid?
Example:
{"dxsEntries":[{"dxsId":67109120,"value":3432.959961}],"session":{"sessionId":0,"roleId":0},"status":{"code":0}}

This would be very useful for users like me, that does not own a battery to control the loading process of my car. Further no energy meter is connected to the piko and I could measure the actually "Self-consumption" by calculating:

Self-consumption = Total DC input - Output power

Best regards 

Maik

**Comment by H2CK** [comment]
Hi Maik,
the value of the attribute "Current AC Power" ("dxsId":67109120) is already fetched by this extension from your Kostal inverter. The value is propagated to the CCU variable ....ACPower by the script.

Your calculation would only calculate the internal self-consumption of your inverter itself (loss of conversion from DC to AC), but not the power consumption in your household. I think your intention was not to just calculate the loss of power with the inverter.

Using the variable .....ConsumptionExt and ....ConsumptionInt you can calculate your current consumption (overall consumption = ConsumptionExt + ConsumptionInt).
If your ConsumptionExt is greater than zero you are retrieving power from the grid.
If your ConsumptionInt is less than ACPower you are feeding into the grid (FeedingPowerIntoTheGrid = ACPower - ConsumptionInt).

The attributes ConsumptionInt and ConsumptionExt are only set if you have an BA sensor installed beside to your converter (and connected to the inverter - I am not sure if newer models have an integrated BA sensor). Without an BA sensor there is no possibility to get some information from your inverter of how much of your produced power is consumed in your household and how much is feed into the grid..

I hope this explanation helps. At least I do not see the need to add anything to the extension, since the requested attribute is already available.
